apiVersion: v1
kind: Template
metadata:
  name: ${APPLICATION_NAME}
  annotations:
    description: Template for the application
    tags: app,java,solr
    iconClass: icon-rh-openjdk
    openshift.io/provider-display-name: Red Hat, Inc.
    openshift.io/support-url: https://access.redhat.com
labels:
  template: ${APPLICATION_NAME}
  app: ${APPLICATION_NAME}
objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: "${APPLICATION_NAME}"
  spec:
    ports:
    - port: 8983
      name: 8983-tcp
      protocol: TCP
    selector:
      app: "${APPLICATION_NAME}"
    # sessionAffinity: None
- apiVersion: v1
  kind: Route
  metadata:
    name: "${APPLICATION_NAME}"
  spec:
    to:
      kind: Service
      name: "${APPLICATION_NAME}"
      weight: 100
    port:
      targetPort: 8983-tcp
    wildcardPolicy: None
- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: "${APPLICATION_NAME}"
  spec:
    replicas: "${{REPLICAS}}"
    serviceName: "${APPLICATION_NAME}"
    selector:
      matchLabels:
        app: "${APPLICATION_NAME}"
    strategy:
      type: Rolling
      rollingParams:
        updatePeriodSeconds: 1
        intervalSeconds: 1
        timeoutSeconds: 600
        maxUnavailable: 25%
        maxSurge: 25%
      activeDeadlineSeconds: 21600
    template:
      metadata:
        labels:
          app: "${APPLICATION_NAME}"
      spec:
        containers:
        - name: "${APPLICATION_NAME}"
          image: "docker-registry.default.svc:5000/${IMAGE_NAMESPACE}/${APPLICATION_NAME}:${IMAGE_TAG}"
          env:
            # cat /etc/default/solr.in.sh 
            # - name: "SOLR_HOME" ## Deprecated
            #   value: "/opt/solr/server/solr"
            # - name: "ENABLE_REMOTE_JMX_OPTS"
            #   value: "true"
            - name: "ZK_HOST"
              value: "zookeeper-0.zookeeper-server:2181,zookeeper-1.zookeeper-server:2181,zookeeper-2.zookeeper-server:2181"
          ports:
          - containerPort: 8983
            protocol: TCP
          imagePullPolicy: Always
          # https://issues.apache.org/jira/browse/SOLR-11126
          readinessProbe:
            httpGet:
              # scheme: 'ternary "HTTPS" "HTTP""'
              path: /solr/admin/info/system
              port: 8983
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
          livenessProbe:
            httpGet:
              # scheme: 'ternary "HTTPS" "HTTP""'
              path: /solr/admin/info/system
              port: 8983
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
          resources:
            limits:
              cpu: "${{CPU_LIMIT}}"
              memory: "${{MEMORY_LIMIT}}"
            requests:
              cpu: "${{CPU_REQUEST}}"
              memory: "${{MEMORY_REQUEST}}"
          volumeMounts:
          - name: "${APPLICATION_NAME}-data"
            mountPath: "${MOUNT_PATH}"
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        securityContext: {}
        volumes:
        - name: "${APPLICATION_NAME}-data"
          persistentVolumeClaim:
            claimName: "${APPLICATION_NAME}-data"
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: "${APPLICATION_NAME}-data"
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: "${{PERSISTENT_VOLUME_SIZE}}"
parameters:
- name: APPLICATION_NAME
  displayName: Name
  description: "The name of the application."
  required: true
  value: solr
- name: REPLICAS
  displayName: Number of replicas
  description: Number of application replicas.
  required: true
  value: "3"
- name: IMAGE_NAMESPACE
  displayName: Image Namespace
  required: false
  description: The namespace of the OpenShift project containing the imagestream for the application.
  value: solr
- name: IMAGE_TAG
  displayName: Environment TAG name
  description: Tag of the solr image
  value: "8.4.1"
  required: false
- name: PERSISTENT_VOLUME_SIZE
  displayName: Persistent Volume Size
  description: The size of the persistent volume , e.g. 512Mi, 1Gi, 2Gi.
  required: false
  value: 1Gi
- name: CPU_REQUEST
  displayName: CPU Request
  description: CPU request.
  required: false
  value: "1"
- name: CPU_LIMIT
  displayName: CPU Limit
  description: CPU limit.
  required: false
  value: "2"
- name: MEMORY_REQUEST
  displayName: Memory Request
  description: Memory request.
  required: false
  value: "2048Mi"
- name: MEMORY_LIMIT
  displayName: Memory Limit
  description: Memory limit.
  required: false
  value: "4096Mi"
# - name: MOUNT_PATH # Deprecated
#   displayName: Mount Path
#   description: "The path to mount the persistent volume."
#   value: "/opt/solr/server/solr/mycores"
#   required: false