apiVersion: v1
kind: Template
metadata:
  name: ${APPLICATION_NAME}
  annotations:
    description: Template for the application
    tags: app,java,solr
    iconClass: icon-rh-openjdk
    openshift.io/provider-display-name: Red Hat, Inc.
    openshift.io/support-url: https://access.redhat.com
labels:
  template: ${APPLICATION_NAME}
  app: ${APPLICATION_NAME}
objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: "${APPLICATION_NAME}"
  spec:
    ports:
    - port: 8983
      name: 8983-tcp
      protocol: TCP
    selector:
      app: "${APPLICATION_NAME}"
    # sessionAffinity: None
- apiVersion: v1
  kind: Route
  metadata:
    name: "${APPLICATION_NAME}"
  spec:
    to:
      kind: Service
      name: "${APPLICATION_NAME}"
      weight: 100
    port:
      targetPort: 8983-tcp
    wildcardPolicy: None
- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: "${APPLICATION_NAME}"
  spec:
    replicas: "${{REPLICAS}}"
    serviceName: "${APPLICATION_NAME}"
    selector:
      matchLabels:
        app: "${APPLICATION_NAME}"
    strategy:
      type: Rolling
      rollingParams:
        updatePeriodSeconds: 1
        intervalSeconds: 1
        timeoutSeconds: 600
        maxUnavailable: 25%
        maxSurge: 25%
      activeDeadlineSeconds: 21600
    template:
      metadata:
        labels:
          app: "${APPLICATION_NAME}"
      spec:
        containers:
        - name: "${APPLICATION_NAME}"
          image: "${IMAGE_NAME}:${IMAGE_TAG}"
          env:
            # cat /etc/default/solr.in.sh 
            - name: "ZK_HOST"
              value: "zookeeper-0.zookeeper-server:2181,zookeeper-1.zookeeper-server:2181,zookeeper-2.zookeeper-server:2181"
            # Maybe solution for "Solr registered with IP". Should be tested.
            # https://lucene.apache.org/solr/guide/8_4/taking-solr-to-production.html#solr-hostname
            # - name: "SOLR_HOST"
            #   valueFrom:
            #     firldRef: metadata.name
          ports:
          - containerPort: 8983
            protocol: TCP
          imagePullPolicy: Always
          # https://issues.apache.org/jira/browse/SOLR-11126
          readinessProbe:
            httpGet:
              path: /solr/admin/info/system/health
              port: 8983
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
          livenessProbe:
            httpGet:
              path: /solr/admin/info/system/health
              port: 8983
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
          resources:
            limits:
              cpu: "${{CPU_LIMIT}}"
              memory: "${{MEMORY_LIMIT}}"
            requests:
              cpu: "${{CPU_REQUEST}}"
              memory: "${{MEMORY_REQUEST}}"
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        securityContext: {}
parameters:
- name: APPLICATION_NAME
  displayName: Application name
  description: "The name of the application."
  required: true
  value: solr
- name: REPLICAS
  displayName: Number of replicas
  description: Number of application replicas.
  required: true
  value: "3"
- name: IMAGE_NAME
  displayName: Name of the image
  description: "The name of the image."
  required: true
  value: solr
- name: IMAGE_TAG
  displayName: Environment TAG name
  description: Tag of the solr image
  value: "8.4.1"
  required: false
- name: CPU_REQUEST
  displayName: CPU Request
  description: CPU request.
  required: false
  value: "1"
- name: CPU_LIMIT
  displayName: CPU Limit
  description: CPU limit.
  required: false
  value: "2"
- name: MEMORY_REQUEST
  displayName: Memory Request
  description: Memory request.
  required: false
  value: "2048Mi"
- name: MEMORY_LIMIT
  displayName: Memory Limit
  description: Memory limit.
  required: false
  value: "4096Mi"