apiVersion: v1
kind: Template
metadata:
  name: ${APPLICATION_NAME}
  annotations:
    description: Template for the application
    tags: app,java,solr
    iconClass: icon-rh-openjdk
    openshift.io/provider-display-name: Red Hat, Inc.
    openshift.io/support-url: https://access.redhat.com
labels:
  template: ${APPLICATION_NAME}
  app: ${APPLICATION_NAME}
objects:
- kind: Service
  apiVersion: v1
  metadata:
    name: "${APPLICATION_NAME}"
    labels:
      app: "${APPLICATION_NAME}"
  spec:
    ports:
    - name: 8983-tcp
      protocol: TCP
      port: 8983
      targetPort: 8983
    selector:
      app: "${APPLICATION_NAME}"
      deploymentconfig: "${APPLICATION_NAME}"
    type: ClusterIP
    sessionAffinity: None
- kind: Route
  apiVersion: v1
  metadata:
    name: "${APPLICATION_NAME}"
  spec:
    to:
      kind: Service
      name: "${APPLICATION_NAME}"
      weight: 100
    port:
      targetPort: 8983-tcp
    wildcardPolicy: None
- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: "${APPLICATION_NAME}"
    labels:
      app: "${APPLICATION_NAME}"
      template: "${APPLICATION_NAME}-deployment-template"
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: "${PERSISTENT_VOLUME_SIZE}"
- kind: StatefulSet
  apiVersion: v1
  metadata:
    name: "${APPLICATION_NAME}"
    labels:
      app: "${APPLICATION_NAME}"
  spec:
    replicas: 3
    selector:
      app: "${APPLICATION_NAME}"
    strategy:
      type: Rolling
      rollingParams:
        updatePeriodSeconds: 1
        intervalSeconds: 1
        timeoutSeconds: 600
        maxUnavailable: 25%
        maxSurge: 25%
      activeDeadlineSeconds: 21600
    template:
      metadata:
        labels:
          app: "${APPLICATION_NAME}"
      spec:
        containers:
        - name: "${APPLICATION_NAME}"
          # cat /etc/default/solr.in.sh
          env:
            # - name: "SOLR_HOME"
            #   value: "/opt/solr/server/solr"
            - name: "ENABLE_REMOTE_JMX_OPTS"
              value: "true"
          ports:
          - containerPort: 8983
            protocol: TCP
          terminationMessagePath: "/dev/termination-log"
          terminationMessagePolicy: File
          imagePullPolicy: Always
          # https://issues.apache.org/jira/browse/SOLR-11126
          readinessProbe:
            httpGet:
              # scheme: 'ternary "HTTPS" "HTTP""'
              path: "/solr/admin/info/system"
              port: "8983"
            periodSeconds: ${LIVENESS_HEALTH_ENDPOINT}
            initialDelaySeconds: "60"
            timeoutSeconds: "10"
          livenessProbe:
            httpGet:
              # scheme: 'ternary "HTTPS" "HTTP""'
              path: "/solr/admin/info/system"
              port: "8983"
            periodSeconds: "${{PROBE_PERIOD}}"
            initialDelaySeconds: "60"
            timeoutSeconds: "10"
          resources:
            limits:
              cpu: 2
              memory: 4096Mi
            requests:
              cpu: 1
              memory: 2048Mi
          volumeMounts:
          - name: "${APPLICATION_NAME}-data"
            mountPath: "${MOUNT_PATH}"
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        securityContext: {}
        volumes:
        - name: "${APPLICATION_NAME}-data"
          persistentVolumeClaim:
            claimName: "${APPLICATION_NAME}"
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - "${APPLICATION_NAME}"
        from:
          kind: ImageStreamTag
          namespace: "${IMAGE_NAMESPACE}"
          name: "${APPLICATION_NAME}:${IMAGE_TAG}"
parameters:
- name: APPLICATION_NAME
  displayName: Name
  description: "The name of the application."
  required: true
  value: solr
- name: IMAGE_NAMESPACE
  displayName: Image Namespace
  required: false
  description: The namespace of the OpenShift project containing the imagestream for the application.
  value: solr
- name: IMAGE_TAG
  displayName: Environment TAG name
  description: Tag of the solr image
  value: latest
  required: false
- name: PERSISTENT_VOLUME_SIZE
  displayName: Persistent Volume Size
  description: The size of the persistent volume , e.g. 512Mi, 1Gi, 2Gi.
  required: false
  value: 1Gi
- name: MOUNT_PATH
  displayName: Mount Path
  description: "The path to mount the persistent volume."
  value: "/opt/solr/server/solr/mycores"
  required: false